In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

In [19]:
# defines the reward/connection graph
r = np.array([[0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 10],
              [0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, -1,  -1,  -1, -1, -1, -1, 0, 0, 0],
              [0, 0, 0, -1,  -2,  -2, -2, -2, -1, 0, 0, 0],
              [0, 0, 0, -1,  -2,  -3, -3, -2, -1, 0, 0, 0],
              [0, 0, 0, -1,  -2,  -3, -2, -2, -1, 0, 0, 0],
              [0, 0, 0, -1,  -2,  -3, -2, -1, -1, 0, 0, 0],
              [0, 0, 0, -1,  -2,  -2, -2, -1, 0, 0, 0, 0],
              [0, 0, 0, -1,  -1,  -1, -1, -1, 0, 0, 0, 0],
              [0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0]]).astype("float32")
q_value = np.array([ [np.zeros_like(r)], [np.zeros_like(r)], [np.zeros_like(r)],[np.zeros_like(r)]])


0.25

In [ ]:
def update_q(state, next_state, action, alpha, gamma):
    rsa = r[state, action]
    qsa = q[state, action]
    new_q = qsa + alpha * (rsa + gamma * max(q[next_state, :]) - qsa)
    q[state, action] = new_q
    # renormalize row to be between 0 and 1
    rn = q[state][q[state] > 0] / np.sum(q[state][q[state] > 0])
    q[state][q[state] > 0] = rn
return r[state, action]

In [38]:
rsa = r[row, col]
qsa = q_value[action, row, col]
new_q = qsa + alpha * (rsa + gamma * max(q_value[:, row, col]) - qsa)
q_value[action, row, col] = new_q


[ True  True  True False False False False False False  True  True  True]


In [22]:
A = np.array([[[ 0.1,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])
A

array([[[ 0.1,  1. ],
        [ 2. ,  3. ],
        [ 4. ,  5. ],
        [ 6. ,  7. ]],

       [[ 8. ,  9. ],
        [10. , 11. ],
        [12. , 13. ],
        [14. , 15. ]],

       [[16. , 17. ],
        [18. , 19. ],
        [20. , 21. ],
        [22. , 23. ]]])

In [58]:
gamma = 0.8
alpha = 1
n_episodes = 1E3
n_row = 12
n_col = 12
n_actions = 4
epsilon = 0.05
for e in range(int(n_episodes)):
    

[[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0