In [1]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(20):
    env.render()
    env.step(env.action_space.sample())

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [2]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.01234321  0.00553692 -0.01972069  0.01826245]
[ 0.01245395 -0.18929675 -0.01935544  0.30465861]
[ 0.00866802  0.00609561 -0.01326227  0.00593483]
[ 0.00878993  0.20140523 -0.01314357 -0.29090282]
[ 0.01281803  0.00647313 -0.01896163 -0.00239403]
[ 0.01294749 -0.18837182 -0.01900951  0.28424647]
[ 0.00918006  0.00701602 -0.01332458 -0.0143708 ]
[ 0.00932038  0.20232651 -0.01361199 -0.31122783]
[ 0.01336691  0.39763972 -0.01983655 -0.60817231]
[ 0.0213197   0.59303329 -0.032      -0.90703658]
[ 0.03318037  0.39835886 -0.05014073 -0.62458081]
[ 0.04114755  0.59414364 -0.06263235 -0.93262409]
[ 0.05303042  0.39992014 -0.08128483 -0.66026196]
[ 0.06102882  0.59607355 -0.09449007 -0.97739202]
[ 0.07295029  0.40233693 -0.11403791 -0.7158222 ]
[ 0.08099703  0.59883715 -0.12835435 -1.04211257]
[ 0.09297377  0.79540846 -0.1491966  -1.37217665]
[ 0.10888194  0.60243353 -0.17664013 -1.12963119]
[

[-0.09598277 -0.57652577  0.03079747  0.70885141]
[-0.10751328 -0.38184363  0.0449745   0.4260197 ]
[-0.11515015 -0.5775728   0.05349489  0.73253463]
[-0.12670161 -0.77339153  0.06814558  1.04156254]
[-0.14216944 -0.96934921  0.08897683  1.35483613]
[-0.16155642 -1.16546806  0.11607356  1.67397537]
[-0.18486579 -1.36173053  0.14955306  2.00043716]
[-0.2121004  -1.1684538   0.18956181  1.75756305]
Episode finished after 29 timesteps
[ 0.03145697  0.00883065  0.04602412 -0.00028912]
[ 0.03163358 -0.1869201   0.04601834  0.3065524 ]
[0.02789518 0.00751692 0.05214939 0.02873024]
[ 0.02804551 -0.1883126   0.05272399  0.33740016]
[ 0.02427926 -0.38414364  0.05947199  0.64623221]
[ 0.01659639 -0.58004164  0.07239664  0.95703417]
[ 0.00499556 -0.38596401  0.09153732  0.68794631]
[-0.00272372 -0.58222921  0.10529625  1.007986  ]
[-0.01436831 -0.77858724  0.12545597  1.33179165]
[-0.02994005 -0.58525066  0.1520918   1.08085339]
[-0.04164507 -0.78201718  0.17370887  1.41713887]
[-0.05728541 -0.58

[ 0.10796591  0.76319494 -0.08239539 -0.95802326]
[ 0.12322981  0.56927174 -0.10155585 -0.69232215]
[ 0.13461524  0.76564506 -0.1154023  -1.01517058]
[ 0.14992814  0.57223536 -0.13570571 -0.76083872]
[ 0.16137285  0.37921791 -0.15092248 -0.51374956]
[ 0.16895721  0.57610722 -0.16119747 -0.84992935]
[ 0.18047935  0.38350715 -0.17819606 -0.61196169]
[ 0.18814949  0.58061304 -0.19043529 -0.9550516 ]
Episode finished after 30 timesteps
[0.03846482 0.04696095 0.00088267 0.01518911]
[ 0.03940404  0.24207023  0.00118645 -0.2772152 ]
[ 0.04424544  0.04693137 -0.00435785  0.0158417 ]
[ 0.04518407 -0.14812781 -0.00404102  0.3071465 ]
[ 0.04222151 -0.34319195  0.00210191  0.59855225]
[ 0.03535767 -0.53834325  0.01407296  0.89189652]
[ 0.02459081 -0.343415    0.03191089  0.60367041]
[ 0.01772251 -0.14875354  0.0439843   0.32120709]
[0.01474744 0.04571534 0.05040844 0.04271311]
[ 0.01566174 -0.15009185  0.0512627   0.35086462]
[0.01265991 0.04426502 0.05827999 0.07477692]
[ 0.01354521 -0.15164191  

In [1]:
import numpy as np

import gym
from gym import error, spaces, utils
from gym.utils import seeding
